In [3]:
import numpy as np

In [2]:
l1=[10,12,13,5]

## creating numpy array (plenty of ways exist)

In [3]:
arr=np.array(l1)

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr=np.array([45,2,35,55,4,60,34])

In [6]:
arr

array([45,  2, 35, 55,  4, 60, 34])

In [7]:
print(arr)

[45  2 35 55  4 60 34]


In [8]:
arr[0]

45

In [9]:
arr[-1]

34

In [10]:
arr[2:5] # 2,3,4

array([35, 55,  4])

In [11]:
arr1=arr[2:5] # slicing does not create a separeate memory location 
# it refers to same / original array , 
# so changes done through slice reflects in main array [ IMPORTANT ]

In [12]:
arr1[0]=100

In [13]:
arr

array([ 45,   2, 100,  55,   4,  60,  34])

In [14]:
arr1=arr.copy() # creates anaother array in different location(xereox copy)

In [15]:
arr1=arr[2:5].copy()

In [16]:
arr1

array([100,  55,   4])

In [17]:
arr

array([ 45,   2, 100,  55,   4,  60,  34])

In [18]:
arr1[0]=200

In [19]:
arr1

array([200,  55,   4])

In [20]:
arr

array([ 45,   2, 100,  55,   4,  60,  34])

In [21]:
arr=np.array([45,2,35,55,4,60,34])

In [22]:
for x in arr:
    print(x)

45
2
35
55
4
60
34


In [23]:
arr.dtype

dtype('int32')

## numpy data types are very influenced by c data types ( so they ar very compicated)

In [24]:
arr1=np.array([12,40,3.7,50])

In [25]:
arr1.dtype

dtype('float64')

In [26]:
arr1

array([12. , 40. ,  3.7, 50. ])

In [27]:
print(arr1)

[12.  40.   3.7 50. ]


In [28]:
arr1=np.array([12,40,3.7,50,'amit'])

In [29]:
arr1

array(['12', '40', '3.7', '50', 'amit'], dtype='<U32')

In [30]:
arr1.dtype

dtype('<U32')

## numpy implecitly determines datatypes of an array by looking at what is stored in array

In [31]:
arr=np.array([10,4,5,6],dtype='float')

In [32]:
arr

array([10.,  4.,  5.,  6.])

In [33]:
arr.dtype

dtype('float64')

In [34]:
arr=np.array([10,4,5,6],dtype='str')

In [35]:
arr

array(['10', '4', '5', '6'], dtype='<U2')

In [36]:
arr.ndim

1

In [37]:
arr[0]

'10'

In [38]:
arr=np.array([45,2,35,55,4,60,34])

In [39]:
arr.ndim

1

In [40]:
arr[0]

45

In [41]:
#  create list of list 
l2=[ [10,20],[30,40],[50,60]  ]
arr=np.array(l2)

In [42]:
arr

array([[10, 20],
       [30, 40],
       [50, 60]])

In [43]:
arr.ndim

2

In [44]:
arr[1][1]

40

In [45]:
arr[1, 1]

40

In [46]:
arr

array([[10, 20],
       [30, 40],
       [50, 60]])

In [47]:
arr.shape # returns a tuple : (no of rows, no of cols)

(3, 2)

In [48]:
arr.shape[0]

3

In [49]:
arr.shape[1]

2

In [50]:
arr=np.array([45,2,35,55,4,60,34])

In [51]:
arr.shape

(7,)

In [52]:
arr.shape[0]

7

In [53]:
len(arr)

7

In [54]:
arr=np.arange(2,10,1)

In [55]:
arr

array([2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
arr=np.arange(2, 10)

In [57]:
arr

array([2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
arr=np.arange(10)

In [59]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
arr=np.arange(0,1,.1)

In [61]:
arr

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [62]:
arr.shape

(10,)

In [63]:
arr=np.arange(0,1,.01)

In [64]:
arr

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99])

In [65]:
arr.shape

(100,)

In [66]:
arr=np.arange(0,1,.001)

In [67]:
arr.shape

(1000,)

In [68]:
arr

array([0.   , 0.001, 0.002, 0.003, 0.004, 0.005, 0.006, 0.007, 0.008,
       0.009, 0.01 , 0.011, 0.012, 0.013, 0.014, 0.015, 0.016, 0.017,
       0.018, 0.019, 0.02 , 0.021, 0.022, 0.023, 0.024, 0.025, 0.026,
       0.027, 0.028, 0.029, 0.03 , 0.031, 0.032, 0.033, 0.034, 0.035,
       0.036, 0.037, 0.038, 0.039, 0.04 , 0.041, 0.042, 0.043, 0.044,
       0.045, 0.046, 0.047, 0.048, 0.049, 0.05 , 0.051, 0.052, 0.053,
       0.054, 0.055, 0.056, 0.057, 0.058, 0.059, 0.06 , 0.061, 0.062,
       0.063, 0.064, 0.065, 0.066, 0.067, 0.068, 0.069, 0.07 , 0.071,
       0.072, 0.073, 0.074, 0.075, 0.076, 0.077, 0.078, 0.079, 0.08 ,
       0.081, 0.082, 0.083, 0.084, 0.085, 0.086, 0.087, 0.088, 0.089,
       0.09 , 0.091, 0.092, 0.093, 0.094, 0.095, 0.096, 0.097, 0.098,
       0.099, 0.1  , 0.101, 0.102, 0.103, 0.104, 0.105, 0.106, 0.107,
       0.108, 0.109, 0.11 , 0.111, 0.112, 0.113, 0.114, 0.115, 0.116,
       0.117, 0.118, 0.119, 0.12 , 0.121, 0.122, 0.123, 0.124, 0.125,
       0.126, 0.127,

In [69]:
arr=np.arange(1, 7)

In [70]:
arr

array([1, 2, 3, 4, 5, 6])

In [71]:
arr.ndim

1

In [72]:
arr.shape

(6,)

In [73]:
arr1=arr.reshape(3, 2)

In [74]:
arr1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [75]:
arr

array([1, 2, 3, 4, 5, 6])

In [76]:
arr1=arr.reshape(2, 3)

In [77]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
arr1=arr.reshape(6,1)

In [79]:
arr1

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [80]:
arr1=arr.reshape(1,6)

In [81]:
arr1

array([[1, 2, 3, 4, 5, 6]])

In [82]:
arr

array([1, 2, 3, 4, 5, 6])

In [83]:
arr[1] # single index == 1-D

2

In [84]:
arr1[0,1] # double index == 2-D

2

In [85]:
arr1[0][1]

2

In [86]:
arr=np.arange(1,19)

In [87]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [88]:
arr.shape

(18,)

In [89]:
arr1=arr.reshape(3,2,3) # converting a 1D array to 3D array

In [90]:
arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [91]:
arr1[1,0,2]

9

In [92]:
arr1[2,0,1]

14

In [93]:
arr=np.arange(48).reshape(2,3,2,2,2)

In [94]:
arr.ndim

5

In [95]:
arr.shape

(2, 3, 2, 2, 2)

In [96]:
arr1=np.arange(1,6)

In [97]:
arr1

array([1, 2, 3, 4, 5])

In [98]:
# classical way of adding 10 to each cell/element
# NOT AT ALL APPRECIATED
l=[]
for x in arr1:
    l.append(x+10)
arr2=np.array(l)

In [99]:
arr2

array([11, 12, 13, 14, 15])

In [100]:
arr11=arr1+10

In [101]:
arr11

array([11, 12, 13, 14, 15])

In [102]:
arr1*2

array([ 2,  4,  6,  8, 10])

## applying any operations with numpy array will execute this operation witj every element of array , no need to code explicit  loop

## this is known as 'VECTORIZATION'
## if 2 or more arrays are involved , they MUST BE OF SAME SIZE

In [103]:
arr2=np.array([100,200,100,200,100])

In [104]:
arr1

array([1, 2, 3, 4, 5])

In [105]:
arr33=arr2+arr1 #vectorization

In [106]:
arr33

array([101, 202, 103, 204, 105])

In [107]:
arr1

array([1, 2, 3, 4, 5])

In [108]:
arr2=np.array([100,200,100,200])

In [109]:
arr2d=np.arange(1,5).reshape(2,2)

In [110]:
arr2d

array([[1, 2],
       [3, 4]])

In [111]:
arr2d1=arr2d+100

In [112]:
arr2d1

array([[101, 102],
       [103, 104]])

In [113]:
arr2d=np.arange(1,13).reshape(4,3)

In [114]:
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [115]:
arr1

array([1, 2, 3, 4, 5])

In [116]:
arr1=np.array([100,100,100])

In [117]:
arr2d+arr1

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109],
       [110, 111, 112]])

In [118]:
vec1=np.array([3,5,6]) # row vector == 1D array

In [119]:
vec1

array([3, 5, 6])

In [120]:
vec2=np.array([3,5,6]).reshape(3,1) # column vector == 2D array

In [121]:
vec2

array([[3],
       [5],
       [6]])

In [122]:
arr1

array([100, 100, 100])

In [123]:
arr2

array([100, 200, 100, 200])

In [124]:
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [125]:
vec1

array([3, 5, 6])

In [126]:
arr2d+vec1

array([[ 4,  7,  9],
       [ 7, 10, 12],
       [10, 13, 15],
       [13, 16, 18]])

In [127]:
vec2

array([[3],
       [5],
       [6]])

In [128]:
vec2=np.array([3,4,5,6]).reshape(4,1)

In [129]:
vec2.shape

(4, 1)

In [130]:
arr2d+vec2

array([[ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14],
       [16, 17, 18]])

In [131]:
arr=np.zeros(5)

In [132]:
arr


array([0., 0., 0., 0., 0.])

In [133]:
arr=np.zeros( (2,3)  )

In [134]:
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [135]:
arr=np.ones(5)

In [136]:
arr

array([1., 1., 1., 1., 1.])

In [137]:
arr

array([1., 1., 1., 1., 1.])

In [138]:
arr=np.ones( (2,3) )

In [139]:
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [140]:
arr=np.identity(3)

In [141]:
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [142]:
arr=np.eye(3)

In [143]:
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [144]:
arr=np.ones( (3,4) )*10

In [145]:
arr

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [146]:
arr.dtype

dtype('float64')

In [147]:
arr=np.ones( (3,4) ,dtype='int')*10

In [148]:
arr

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [149]:
arr.dtype

dtype('int32')

In [150]:
arr=np.random.rand(5) # values >0 between >=0 and < 1

In [151]:
arr

array([0.549472  , 0.51191259, 0.5172115 , 0.25877679, 0.89501234])

In [152]:
arr=np.random.rand( 2,3) 

In [153]:
arr

array([[0.72067786, 0.43259745, 0.33275954],
       [0.17885529, 0.25651518, 0.27077479]])

In [154]:
arr=np.random.rand( 2,3,2) 

In [155]:
arr=np.random.normal(loc=10,scale=2,size=(2,3))

In [156]:
arr

array([[10.33825726,  9.84984184,  5.39430466],
       [12.67622038,  8.8185626 ,  8.91941233]])

In [157]:
arr=np.random.randn(10)  # np.random.normal(loc=0,scale=1,size=10)

In [158]:
arr

array([-0.10239869, -1.73252707,  1.6088809 , -0.14220798,  1.4700144 ,
        0.4613364 ,  1.25654979, -0.15824535, -0.37448965, -1.7671651 ])

In [159]:
arr=np.random.randint(low=10,high=15,size=10)

In [160]:
arr

array([10, 11, 10, 11, 11, 14, 12, 10, 10, 11])

In [161]:
arr=np.random.randint(low=10,high=15,size=(2,3))

In [162]:
arr

array([[10, 13, 11],
       [10, 11, 12]])

In [163]:
arr=np.random.rand(5)

In [164]:
np.random.seed(112)
arr=np.random.rand(5)
print(arr)

[0.37505713 0.64030462 0.95001658 0.0756772  0.77692966]


In [165]:
np.random.seed(112)
arr=np.random.randint(low=10,high=50,size=(6,6))

In [166]:
arr

array([[46, 36, 11, 15, 49, 30],
       [39, 14, 16, 39, 15, 38],
       [47, 18, 13, 36, 20, 20],
       [47, 28, 24, 42, 44, 23],
       [24, 24, 34, 12, 11, 41],
       [13, 40, 44, 45, 33, 42]])

## can use slicing in place of index

In [167]:
arr[ 1:4 , 0:3 ]

array([[39, 14, 16],
       [47, 18, 13],
       [47, 28, 24]])

In [168]:
arr[:3,:3]

array([[46, 36, 11],
       [39, 14, 16],
       [47, 18, 13]])

In [169]:
arr[-2:,-3:]

array([[12, 11, 41],
       [45, 33, 42]])

In [170]:
arr[ 1:4 , 0:3 ]=100

In [171]:
arr

array([[ 46,  36,  11,  15,  49,  30],
       [100, 100, 100,  39,  15,  38],
       [100, 100, 100,  36,  20,  20],
       [100, 100, 100,  42,  44,  23],
       [ 24,  24,  34,  12,  11,  41],
       [ 13,  40,  44,  45,  33,  42]])

In [172]:
arr[:,2]

array([ 11, 100, 100, 100,  34,  44])

In [173]:
arr[:,2]=90

In [174]:
arr

array([[ 46,  36,  90,  15,  49,  30],
       [100, 100,  90,  39,  15,  38],
       [100, 100,  90,  36,  20,  20],
       [100, 100,  90,  42,  44,  23],
       [ 24,  24,  90,  12,  11,  41],
       [ 13,  40,  90,  45,  33,  42]])

In [175]:
agearr=np.array([19,23,16,25,18,27])

In [176]:
boolarr=np.array([True,False,True,False,True,False])

### boolean array can be used as an index !!!!!! --> filtering

In [177]:
agearr[boolarr]

array([19, 16, 18])

In [178]:
boolarr=agearr<20  

In [179]:
agearr[boolarr]

array([19, 16, 18])

In [180]:
agearr[ agearr < 20 ] # finding all values < 20 ---> filtering !!!

array([19, 16, 18])

In [181]:
agearr

array([19, 23, 16, 25, 18, 27])

In [182]:
np.max(agearr)

27

In [183]:
np.argmax(agearr)

5

In [184]:
agearr >=15

array([ True,  True,  True,  True,  True,  True])

In [185]:
agearr <=25

array([ True,  True,  True,  True,  True, False])

In [186]:
(agearr >=15)  & (agearr <=25)  # and gating ==> &

array([ True,  True,  True,  True,  True, False])

In [187]:
agearr[ (agearr >=15)  & (agearr <=25)  ]

array([19, 23, 16, 25, 18])

In [188]:
agearr

array([19, 23, 16, 25, 18, 27])

In [189]:
agearr[ (agearr <=15)  | (agearr >=25)  ] # or gating ==> |

array([25, 27])

In [190]:
agearr[  agearr >= 20  ]

array([23, 25, 27])

In [191]:
agearr[  ~(agearr >= 20)  ] # complementing 

array([19, 16, 18])

In [192]:
np.random.seed(112)
arr=np.random.randint(low=10,high=50,size=(6,6))

In [193]:
arr

array([[46, 36, 11, 15, 49, 30],
       [39, 14, 16, 39, 15, 38],
       [47, 18, 13, 36, 20, 20],
       [47, 28, 24, 42, 44, 23],
       [24, 24, 34, 12, 11, 41],
       [13, 40, 44, 45, 33, 42]])

In [194]:
arr[:,-1]>40 # 

array([False, False, False, False,  True,  True])

In [195]:
arr[:,-1][ arr[:,-1]>40 ]

array([41, 42])

In [196]:
agearr

array([19, 23, 16, 25, 18, 27])

In [197]:
agearr.max()

27

In [198]:
np.max(agearr) # called through np module

27

In [199]:
np.min(agearr)

16

In [200]:
np.argmin(agearr)

2

In [201]:
arr

array([[46, 36, 11, 15, 49, 30],
       [39, 14, 16, 39, 15, 38],
       [47, 18, 13, 36, 20, 20],
       [47, 28, 24, 42, 44, 23],
       [24, 24, 34, 12, 11, 41],
       [13, 40, 44, 45, 33, 42]])

In [202]:
np.max(arr)

49

In [203]:
np.max(arr,axis=0) # column wise max , traversing across rows 

array([47, 40, 44, 45, 49, 42])

In [204]:
np.max(arr,axis=1) # row wise max

array([49, 39, 47, 47, 41, 45])

In [205]:
arr[:,0]

array([46, 39, 47, 47, 24, 13])

In [206]:
np.max(arr[:,3])

45

## mean/meidan can be used as predicted value 
## median is always safer than mean

In [207]:
prices=np.array([5500,5100,5000,6000,6700,5100,6400])

In [208]:
avg=np.mean(prices)

In [209]:
avg

5685.714285714285

In [210]:
prices - avg

array([-185.71428571, -585.71428571, -685.71428571,  314.28571429,
       1014.28571429, -585.71428571,  714.28571429])

In [211]:
np.sum(prices - avg)

2.7284841053187847e-12

In [212]:
np.mean(prices - avg)

3.897834436169692e-13

In [213]:
(prices - avg)**2

array([  34489.79591837,  343061.2244898 ,  470204.08163265,
         98775.51020408, 1028775.51020408,  343061.2244898 ,
        510204.08163265])

In [214]:
np.mean((prices - avg)**2)  # mean of squared error -> variance

404081.63265306124

In [215]:
np.var(prices) # for getting variance

404081.63265306124

In [216]:
np.sqrt(np.mean((prices - avg )**2)) # square root of variance is standard deviation

635.6741560367711

In [217]:
np.std(prices)

635.6741560367711

In [218]:
avg

5685.714285714285

## OUTLIERS

In [5]:
agearr=np.array([19, 23, 16, 25, 18, 27, 14, 15, 24, 15, 16, 17, 18, 23, 25])

In [6]:
agearr

array([19, 23, 16, 25, 18, 27, 14, 15, 24, 15, 16, 17, 18, 23, 25])

In [7]:
iqr=np.quantile(agearr,q=.75)-np.quantile(agearr,q=.25)

In [8]:
iqr

7.5

In [9]:
calcmax = np.quantile(agearr, q=.75) + 1.5*iqr

In [10]:
calcmax

34.75

### any values > calcmax --> outlier in upperside

In [11]:
calcmin = np.quantile(agearr, q=.25) - 1.5*iqr

In [12]:
calcmin

4.75

### any values < calcmin --> outlier in lowerside


In [13]:
arr1=np.array(['10','12','13','14'])
arr2=np.array([10,12,13,14])

In [14]:
arr1.dtype

dtype('<U2')

In [15]:
arr3=arr1.astype('int') #converting string array to int array

In [16]:
arr3

array([10, 12, 13, 14])

In [17]:
arr3=arr1.astype(np.int) # converting string array to int array

In [18]:
arr2

array([10, 12, 13, 14])

In [19]:
arr3=arr2.astype('str') # converting int array to string array

In [20]:
arr3

array(['10', '12', '13', '14'], dtype='<U11')

In [21]:
arr1=np.array([True,False,False,True])

In [22]:
arr3=arr1.astype('int')

In [23]:
arr3

array([1, 0, 0, 1])

In [24]:
agearr

array([19, 23, 16, 25, 18, 27, 14, 15, 24, 15, 16, 17, 18, 23, 25])

In [25]:
encoded=np.where(agearr<20,'t','nt')

In [26]:
encoded

array(['t', 'nt', 't', 'nt', 't', 'nt', 't', 't', 'nt', 't', 't', 't',
       't', 'nt', 'nt'], dtype='<U2')

In [27]:
encoded=np.where(agearr<20,1,2)

In [28]:
encoded

array([1, 2, 1, 2, 1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 2])

In [30]:
arr1=np.random.randint(low=5,high=10,size=(4,2))
arr2=np.random.randint(low=5,high=10,size=(3,2))


In [31]:
arr1

array([[9, 8],
       [6, 8],
       [7, 6],
       [5, 9]])

In [32]:
arr2

array([[8, 5],
       [7, 8],
       [7, 7]])

In [33]:
arrx=np.concatenate( [arr1,arr2]  ,axis=0 )

In [34]:
arrx

array([[9, 8],
       [6, 8],
       [7, 6],
       [5, 9],
       [8, 5],
       [7, 8],
       [7, 7]])

In [35]:
arr3=np.random.randint(low=5,high=10,size=(4,2))
arr4=np.random.randint(low=5,high=10,size=(4,3))

In [36]:
arr3

array([[5, 8],
       [9, 6],
       [5, 9],
       [6, 8]])

In [37]:
arr4

array([[6, 9, 5],
       [9, 9, 5],
       [5, 8, 9],
       [8, 8, 7]])

In [38]:
arrx=np.concatenate( [arr3,arr4]  ,axis=1 )

In [39]:
arrx

array([[5, 8, 6, 9, 5],
       [9, 6, 9, 9, 5],
       [5, 9, 5, 8, 9],
       [6, 8, 8, 8, 7]])

In [40]:
arr1

array([[9, 8],
       [6, 8],
       [7, 6],
       [5, 9]])

In [41]:
w=np.array([2,5,7])

In [42]:
w

array([2, 5, 7])

In [43]:
arr1.shape[0]

4

In [44]:
onearray=np.ones(  (arr1.shape[0] ,1) )

In [45]:
onearray

array([[1.],
       [1.],
       [1.],
       [1.]])

In [46]:
arr1=np.concatenate( [ onearray,arr1] , axis=1)

In [47]:
arr1

array([[1., 9., 8.],
       [1., 6., 8.],
       [1., 7., 6.],
       [1., 5., 9.]])

In [48]:
y=np.dot(arr1,w)

In [49]:
y

array([103.,  88.,  79.,  90.])

In [50]:
arr1

array([[1., 9., 8.],
       [1., 6., 8.],
       [1., 7., 6.],
       [1., 5., 9.]])

In [51]:
arr1.transpose()

array([[1., 1., 1., 1.],
       [9., 6., 7., 5.],
       [8., 8., 6., 9.]])

In [52]:
arr1.T

array([[1., 1., 1., 1.],
       [9., 6., 7., 5.],
       [8., 8., 6., 9.]])

In [53]:
mat1=np.array([[2,3,4],[4,6,8],[6,9,12]])

In [54]:
mat1

array([[ 2,  3,  4],
       [ 4,  6,  8],
       [ 6,  9, 12]])

In [55]:
np.linalg.det(mat1) # linear algebra module : np.linalg
# above matrix in singular as its determinant is zero 

0.0

In [56]:
arr3=np.random.randint(low=5,high=10,size=(4,4))

In [57]:
arr3

array([[8, 9, 9, 9],
       [6, 8, 7, 9],
       [5, 9, 9, 7],
       [8, 5, 7, 6]])

In [58]:
np.linalg.det(arr3)

57.00000000000001

In [59]:
np.linalg.inv(arr3)

array([[ 1.21052632, -0.63157895, -0.47368421, -0.31578947],
       [ 2.12280702, -1.03508772, -0.52631579, -1.01754386],
       [-1.77192982,  0.64912281,  0.73684211,  0.8245614 ],
       [-1.31578947,  0.94736842,  0.21052632,  0.47368421]])

In [61]:
np.linalg.matrix_rank(mat1)

1

In [62]:
mat1

array([[ 2,  3,  4],
       [ 4,  6,  8],
       [ 6,  9, 12]])