## Regression using Scikit-Learn ( python module for Machine Learning)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn import linear_model

In [4]:
df=pd.read_csv("data/bp-age.csv")

In [5]:
df.head()

bp  age  weight
0  132   52     173
1  143   59     184
2  153   67     194
3  162   73     211
4  154   64     196

In [7]:
y=df['bp'].values
x=df['age'].values

In [8]:
y

array([132, 143, 153, 162, 154, 168, 137, 149, 159, 128, 166], dtype=int64)

In [9]:
x

array([52, 59, 67, 73, 64, 74, 54, 61, 65, 46, 72], dtype=int64)

## in scikit-learn independent variables must be in 2D

In [10]:
x=x.reshape(df.shape[0], 1)

In [11]:
x

array([[52],
       [59],
       [67],
       [73],
       [64],
       [74],
       [54],
       [61],
       [65],
       [46],
       [72]], dtype=int64)

In [12]:
x.ndim

2

In [13]:
x1=(x-x.mean())/x.std()

In [14]:
# create model object
model=linear_model.LinearRegression()

In [15]:
# ML happens here/model parameters are calculated
model.fit(x1, y)

LinearRegression()

In [16]:
# model.c0
model.intercept_

150.0909090909091

In [18]:
model.coef_

array([12.71585675])

In [19]:
pred=model.predict(x1)

In [20]:
y=df['bp']
X=df[['age', 'weight']]
# 2 independent variables, multiple LR
# all these are in series, dataframe (pandas)

In [21]:
model=linear_model.LinearRegression()
model.fit(X, y) # no 'reshape' required as X is already in 2D

LinearRegression()

In [22]:
model.intercept_

30.994102952348328

In [23]:
model.coef_

array([0.86141469, 0.3348592 ])

In [24]:
pred=model.predict(X)

In [25]:
pred

array([133.71830776, 143.43166173, 153.6715712 , 164.53266567,
       151.75704553, 168.40781313, 140.46402509, 146.49392789,
       156.30191139, 126.54066446, 165.68040616])